### ISSUE TITLE
qb-log 

### ISSUE THREAD

**Issue by rayidkhan** [rohKane/kane-qb-inventory#2]
the qb-log link is not working i have installed another qb-log but its giving the error
![image](https://github.com/rohKane/kane-qb-inventory/assets/172207102/96aa29fb-3116-4627-9010-6698f0bc82ac)

**Comment by rohKane** [comment]
Hmm, you should open issue on qbcore github qb-log not here

**Comment by rayidkhan** [comment]
The link which u have given of qblogs for the dependency is not working fix
that

**Comment by rohKane** [comment]
Google is your friend
